AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  NombreVPC:
    Type: String
    Default: NMP-Servicios
  ApiAlbNumber:
    Type: String
    Default: "1"
  ClusterName:
    Type: String
    Description: Nombre de la consultora
  ServiceName:
    Type: String
    Description: Nombre del microservicio
    Default: paketo
  TaskDefinitionARN:
    Type: String
    Description: ARN de Task Definition
  HealthPath:
    Type: String 
    Description: Path de health del servicio  
  APIBasePath:
    Type: String 
    Description: Basepath en API Gateway
    Default: ""
  ContainerPort:
    Type: Number
    Description: port number exposed from the container image.
    Default: 80
  PrioridadListener:
    Type: Number
    Description: Prioridad de de la regla en el listener. No se debe repetir.

Resources:
    ElasticLoadBalancingV2TargetGroup:
        Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
        Properties:
            HealthCheckIntervalSeconds: 300
            # Hardcode. Cambiar el path por el correspondiente para health
            HealthCheckPath: !Ref HealthPath
            Port: 80
            Protocol: "HTTP"
            HealthCheckPort: "traffic-port"
            HealthCheckProtocol: "HTTP"
            HealthCheckTimeoutSeconds: 5
            UnhealthyThresholdCount: 2
            TargetType: "ip"
            Matcher: 
                HttpCode: "200"
            HealthyThresholdCount: 5
            VpcId: 
              Fn::ImportValue: !Sub "${NombreVPC}-VPC"
            Name: !Sub "${ServiceName}-1"          
            HealthCheckEnabled: true
            TargetGroupAttributes: 
              - 
                Key: "stickiness.enabled"
                Value: "false"
              - 
                Key: "deregistration_delay.timeout_seconds"
                Value: "300"
              - 
                Key: "stickiness.app_cookie.cookie_name"
                Value: ""
              - 
                Key: "stickiness.type"
                Value: "lb_cookie"
              - 
                Key: "stickiness.lb_cookie.duration_seconds"
                Value: "86400"
              - 
                Key: "slow_start.duration_seconds"
                Value: "0"
              - 
                Key: "stickiness.app_cookie.duration_seconds"
                Value: "86400"
              - 
                Key: "load_balancing.algorithm.type"
                Value: "round_robin"

    ALBListenerProdRule:
      Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
      Properties:
        Actions:
          - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
                  Weight: 1
        Conditions:
          - 
            Field: "path-pattern"
            # Hardcode. Cambiar el path por el correspondiente. 
            # Se recomienda que permanezca el wildcard.
            Values: 
              - !Sub "${APIBasePath}*"
        ListenerArn:
          Fn::ImportValue: !Sub "${NombreVPC}-ApiAlbListener${ApiAlbNumber}"
        Priority: !Ref PrioridadListener

    ECSService:
        Type: "AWS::ECS::Service"
        DependsOn:
          - TaskLogGroup
          - ALBListenerProdRule
        Properties:
            ServiceName: !Ref ServiceName
            Cluster: !Ref ClusterName
            LoadBalancers: 
              - 
                TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
                ContainerName: !Ref ServiceName
                ContainerPort: !Ref ContainerPort
            DesiredCount: 1
            LaunchType: "FARGATE"
            PlatformVersion: "1.4.0"
            TaskDefinition: !Ref TaskDefinitionARN
            DeploymentConfiguration: 
                MaximumPercent: 200
                MinimumHealthyPercent: 100
            NetworkConfiguration: 
                AwsvpcConfiguration: 
                    AssignPublicIp: "DISABLED"
                    SecurityGroups: 
                      - !Ref EC2SecurityGroup
                    Subnets: 
                      - Fn::ImportValue: !Sub "${NombreVPC}-PrivateSubnet1a"
            HealthCheckGracePeriodSeconds: 0
            SchedulingStrategy: "REPLICA"
            DeploymentController: 
                Type: "ECS"
            Tags: 
            - Key: cluster_ECS
              Value: !Ref ClusterName
    
    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "SG para ms"
            GroupName: !Sub ${ServiceName}-sg
            VpcId:
              Fn::ImportValue: !Sub "${NombreVPC}-VPC"
            SecurityGroupIngress: 
              - 
                CidrIp: "10.0.0.0/16"
                FromPort: !Ref ContainerPort
                IpProtocol: "tcp"
                ToPort: !Ref ContainerPort
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"

    TaskLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        LogGroupName: !Sub '/ecs/${ClusterName}/${ServiceName}'
        RetentionInDays: 30
        Tags: 
          - Key: cluster_ECS
            Value: !Ref ClusterName        
